import React, { useState, useEffect, useMemo } from 'react';
import { UtensilsCrossed, DollarSign, Package, AlertTriangle, TrendingUp, Save, RefreshCw, Download } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { INITIAL_STOCK_ITEMS, CURRENCY_SYMBOL } from './constants';
import { StockItem, ItemUpdateField } from './types';
import { StockRow } from './components/StockRow';
import { SummaryCard } from './components/SummaryCard';
import { GeminiInsight } from './components/GeminiInsight';
import { AnalyticsDashboard } from './components/AnalyticsDashboard';

const App: React.FC = () => {
  // Load from local storage or use initial
  const [items, setItems] = useState<StockItem[]>(() => {
    const saved = localStorage.getItem('magic_parking_stock_v1');
    return saved ? JSON.parse(saved) : INITIAL_STOCK_ITEMS;
  });

  const [lastSaved, setLastSaved] = useState<Date | null>(null);

  useEffect(() => {
    localStorage.setItem('magic_parking_stock_v1', JSON.stringify(items));
    setLastSaved(new Date());
  }, [items]);

  const handleUpdateItem = (id: string, field: ItemUpdateField, value: number) => {
    setItems((prevItems) =>
      prevItems.map((item) => (item.id === id ? { ...item, [field]: value } : item))
    );
  };

  const resetData = () => {
    if (confirm("Are you sure you want to reset all data for a new day? Opening stock will be reset to today's closing stock.")) {
        setItems(prev => prev.map(item => ({
            ...item,
            opening: item.closing, // Carry over closing to opening
            added: 0,
            damaged: 0,
            closing: 0
        })));
    }
  };

  // Derived Statistics
  const stats = useMemo(() => {
    let totalRevenue = 0;
    let totalSalesCount = 0;
    let totalDamagedCount = 0;
    let totalStockCount = 0;

    items.forEach((item) => {
      const totalItemStock = item.opening + item.added;
      const sales = Math.max(0, totalItemStock - item.damaged - item.closing);
      const revenue = sales * item.price;

      totalRevenue += revenue;
      totalSalesCount += sales;
      totalDamagedCount += item.damaged;
      totalStockCount += item.closing; // Items currently on hand
    });

    return { totalRevenue, totalSalesCount, totalDamagedCount, totalStockCount };
  }, [items]);

  const downloadPDFReport = () => {
    const doc = new jsPDF();
    const dateStr = new Date().toLocaleDateString();
    
    // Header
    doc.setFillColor(249, 115, 22); // Orange-500
    doc.rect(0, 0, 210, 40, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.text("Magic Parking & Restaurant", 14, 20);
    
    doc.setFontSize(12);
    doc.text(`Daily Stock Report - ${dateStr}`, 14, 30);

    // Summary Stats in PDF
    doc.setTextColor(50, 50, 50);
    doc.setFontSize(10);
    doc.text(`Total Revenue: ${stats.totalRevenue.toLocaleString()} ${CURRENCY_SYMBOL}`, 14, 50);
    doc.text(`Total Plates Sold: ${stats.totalSalesCount}`, 14, 55);
    doc.text(`Total Damaged: ${stats.totalDamagedCount}`, 100, 55);

    // Table Data
    const tableColumn = ["Item", "Price", "Open", "Add", "Total", "Bad", "Close", "Sold", "Revenue"];
    const tableRows: any[] = [];

    items.forEach(item => {
      const totalStock = item.opening + item.added;
      const sales = Math.max(0, totalStock - item.damaged - item.closing);
      const revenue = sales * item.price;
      
      const rowData = [
        item.name,
        item.price.toLocaleString(),
        item.opening,
        item.added,
        totalStock,
        item.damaged,
        item.closing,
        sales,
        revenue.toLocaleString()
      ];
      tableRows.push(rowData);
    });

    // Totals Row
    tableRows.push([
        { content: 'TOTALS', colSpan: 7, styles: { fontStyle: 'bold', halign: 'right' } },
        { content: stats.totalSalesCount, styles: { fontStyle: 'bold' } },
        { content: stats.totalRevenue.toLocaleString(), styles: { fontStyle: 'bold' } }
    ]);

    autoTable(doc, {
        startY: 65,
        head: [tableColumn],
        body: tableRows,
        theme: 'grid',
        headStyles: { fillColor: [51, 65, 85], textColor: 255 }, // Slate-700
        styles: { fontSize: 9, cellPadding: 3 },
        columnStyles: {
            0: { cellWidth: 50 }, // Item Name
            8: { fontStyle: 'bold', halign: 'right' } // Revenue
        }
    });

    // Footer
    const pageCount = doc.internal.pages.length - 1; // fix for extra page sometimes
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text("Generated by Magic Parking Manager App", 14, doc.internal.pageSize.height - 10);
    
    doc.save(`Magic_Parking_Report_${dateStr.replace(/\//g, '-')}.pdf`);
  };

  return (
    <div className="min-h-screen bg-slate-50/50 text-slate-800 pb-24 font-sans selection:bg-orange-100 selection:text-orange-900">
      {/* Header */}
      <header className="bg-white/80 backdrop-blur-md border-b border-slate-200 sticky top-0 z-20">
        <div className="max-w-7xl mx-auto px-6 lg:px-8 h-24 flex items-center justify-between">
          <div className="flex items-center space-x-4">
            <div className="bg-gradient-to-br from-orange-500 to-red-600 p-3 rounded-2xl shadow-lg shadow-orange-500/20">
              <UtensilsCrossed className="w-6 h-6 text-white" />
            </div>
            <div>
              <h1 className="text-2xl font-bold text-slate-900 leading-none">Magic Parking</h1>
              <p className="text-sm text-slate-500 font-medium tracking-wide uppercase mt-1">& Restaurant</p>
            </div>
          </div>
          
          <div className="flex items-center space-x-3">
             <button
                onClick={downloadPDFReport}
                className="flex items-center space-x-2 px-4 py-2.5 text-sm font-semibold text-slate-700 bg-white border border-slate-200 hover:bg-slate-50 hover:border-slate-300 rounded-xl transition-all shadow-sm"
                title="Download PDF Report"
             >
                <Download className="w-4 h-4" />
                <span className="hidden sm:inline">PDF Report</span>
             </button>

             <div className="h-8 w-px bg-slate-200 mx-1 hidden sm:block"></div>

             <button
                onClick={resetData}
                className="flex items-center space-x-2 px-4 py-2.5 text-sm font-semibold text-white bg-slate-900 hover:bg-slate-800 rounded-xl transition-all shadow-md hover:shadow-lg"
                title="Start New Day"
             >
                <RefreshCw className="w-4 h-4" />
                <span className="hidden sm:inline">New Day</span>
             </button>
             
             {lastSaved && (
                <div className="hidden lg:flex items-center space-x-1.5 text-xs text-green-600 bg-green-50 px-3 py-1.5 rounded-full border border-green-100 ml-2">
                    <Save className="w-3 h-3" />
                    <span>Auto-saved</span>
                </div>
             )}
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-6 lg:px-8 mt-10">
        
        {/* Summary Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 mb-12">
          <SummaryCard
            title="Today's Revenue"
            value={`${stats.totalRevenue.toLocaleString()} ${CURRENCY_SYMBOL}`}
            icon={DollarSign}
            colorClass="bg-emerald-500"
          />
          <SummaryCard
            title="Plates Sold"
            value={stats.totalSalesCount.toString()}
            icon={TrendingUp}
            colorClass="bg-blue-500"
          />
          <SummaryCard
            title="Available Stock"
            value={stats.totalStockCount.toString()}
            icon={Package}
            colorClass="bg-violet-500"
          />
          <SummaryCard
            title="Recorded Waste"
            value={stats.totalDamagedCount.toString()}
            icon={AlertTriangle}
            colorClass="bg-rose-500"
          />
        </div>

        {/* Main Stock Table */}
        <div className="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden mb-12">
          <div className="px-8 py-6 border-b border-slate-100 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
            <div>
                <h2 className="text-xl font-bold text-slate-800">Inventory Management</h2>
                <p className="text-slate-500 text-sm mt-1">Track opening, closing and sales for today.</p>
            </div>
            <span className="px-4 py-2 bg-slate-50 rounded-lg text-sm font-medium text-slate-600 border border-slate-100">
                {new Date().toLocaleDateString(undefined, { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
            </span>
          </div>
          
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-slate-50/80 text-slate-500 text-xs uppercase tracking-wider font-bold border-b border-slate-200">
                  <th className="py-5 px-4 w-72 pl-8">Item Details</th>
                  <th className="py-5 px-4 text-center">Unit Price</th>
                  <th className="py-5 px-4 text-center">Opening</th>
                  <th className="py-5 px-4 text-center">Added</th>
                  <th className="py-5 px-4 text-center text-slate-400">Total</th>
                  <th className="py-5 px-4 text-center text-red-500">Damaged</th>
                  <th className="py-5 px-4 text-center">Closing</th>
                  <th className="py-5 px-4 text-center text-green-600">Sold</th>
                  <th className="py-5 px-4 text-right pr-8">Total Amount</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 bg-white">
                {items.map((item) => (
                  <StockRow
                    key={item.id}
                    item={item}
                    onUpdate={handleUpdateItem}
                  />
                ))}
              </tbody>
              <tfoot className="bg-slate-50/50 border-t border-slate-200">
                 <tr>
                    <td className="py-6 px-8 font-bold text-slate-700" colSpan={7}>Daily Totals</td>
                    <td className="py-6 px-4 text-center font-bold text-green-700 text-lg">{stats.totalSalesCount}</td>
                    <td className="py-6 px-8 text-right font-bold text-slate-900 text-lg">{stats.totalRevenue.toLocaleString()} <span className="text-sm font-normal text-slate-500">{CURRENCY_SYMBOL}</span></td>
                 </tr>
              </tfoot>
            </table>
          </div>
        </div>

        {/* Analytics Section - Moved Below Table */}
        {stats.totalSalesCount > 0 ? (
           <AnalyticsDashboard items={items} />
        ) : (
           <div className="bg-white border border-dashed border-slate-300 rounded-xl p-8 mb-12 text-center text-slate-500 text-sm">
             <TrendingUp className="w-8 h-8 mx-auto mb-2 opacity-50" />
             Visual analytics will appear here once you start recording sales.
           </div>
        )}

        {/* Gemini Integration */}
        <GeminiInsight items={items} />

      </main>
    </div>
  );
};

export default App;