import { StockItem } from './types';

export const CURRENCY_SYMBOL = 'UGX';

export const INITIAL_STOCK_ITEMS: StockItem[] = [
  {
    id: '1',
    name: 'Katogo and Chicken',
    category: 'Food',
    price: 15000,
    opening: 20,
    added: 0,
    damaged: 0,
    closing: 0,
    imageQuery: 'delicious,food,plate',
  },
  {
    id: '2',
    name: 'Katogo and Fish',
    category: 'Food',
    price: 12000,
    opening: 15,
    added: 0,
    damaged: 0,
    closing: 0,
    imageQuery: 'gourmet,food,plate',
  },
  {
    id: '3',
    name: 'Nile Perch (Empuuta)',
    category: 'Food',
    price: 25000,
    opening: 10,
    added: 0,
    damaged: 0,
    closing: 0,
    imageQuery: 'restaurant,food,plate',
  },
  {
    id: '4',
    name: 'Kigere (Mulokonyi)',
    category: 'Food',
    price: 10000,
    opening: 25,
    added: 0,
    damaged: 0,
    closing: 0,
    imageQuery: 'dinner,food,plate',
  },
  {
    id: '5',
    name: 'African Tea',
    category: 'Drink',
    price: 5000,
    opening: 50,
    added: 0,
    damaged: 0,
    closing: 0,
    imageQuery: 'coffee,cup',
  },
  {
    id: '6',
    name: 'Black Tea',
    category: 'Drink',
    price: 3000,
    opening: 50,
    added: 0,
    damaged: 0,
    closing: 0,
    imageQuery: 'black,coffee,cup',
  },
];